runtime: python38
env: standard
service: default
entrypoint: gunicorn app:app

env_variables:
  CHANNEL_ACCESS_TOKEN : "wSdpCAD2N4wUrjg5vbXhmlMN0eXqq6kRZ+7oWBDPwwgStk/fVPqtcEmhcKQfhW9ubvfV21WYvNGiaQwJv+opfMbMa9HbhYCe6DuSLwePegsLJ0vkS43p3JuRh7jGUPGy7jeVR75y2u8cqwnUi2JzbAdB04t89/1O/w1cDnyilFU="
  CHANNEL_SECRET : "40f4f98e4805a89e13f27f5a0a499f54"
  FIREBASE_ADMIN_KEY_PATH: 'key.json'

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:
- url: .*
  secure: always
  script: auto
