runtime: python38
env: standard
service: default
entrypoint: gunicorn app:app

env_variables:
  CHANNEL_ACCESS_TOKEN : "Z1Azp+0SWGbiZDlKrmFeqUQCdFK0GsYguAx5IZxLF8kQKhaEiH15U6NKglY6lrqsdi0CmjtrrROj/WrZHqvnxaK57e0+UxSxfxeKPeQe3DiLZQyNUNoh8vU672Uixibk+hJdDl8fOcFx9StvDs1jBgdB04t89/1O/w1cDnyilFU="
  CHANNEL_SECRET : "d2451ec1d86379bc572a48672c77a929"
  FIREBASE_ADMIN_KEY_PATH: 'key.json'

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:
- url: .*
  secure: always
  script: auto
